### ISSUE TITLE
5.7和5.6binlog格式不一样？

### ISSUE THREAD

**Issue by ideamean** [go-mysql-org/go-mysql#243]
5.7下update时，canal.RowsEvent中返回新老数据行所有字段，5.6中，只返回了主键id和被update字段？

**Comment by siddontang** [comment]
The binlog image you set may be different between 5.6 and 5.7. For 5.6, maybe minimal, for 5.7 maybe full.

**Comment by holys** [comment]
'binlog_row_image' is introduced since mysql 5.6.2, and mariadb 10.1.6.
> In MySQL 5.5 and earlier, full row images are always used for both before images and after images.

Anyway, `binlog_row_image` should be `FULL`.

ref:
 - https://dev.mysql.com/doc/refman/5.6/en/replication-options-binary-log.html#sysvar_binlog_row_image
- https://mariadb.com/kb/en/library/replication-and-binary-log-server-system-variables/#binlog_row_image

**Comment by dveeden** [comment]
Looks like not setting `binlog_row_image=FULL` is what might be the issue here. Not sure if there is anything in go-mysql that we should change for this.

@lance6716 @atercattus should we close this issue?
