### ISSUE TITLE
wire protocol tests

### ISSUE THREAD

**Issue by kinnera-kokkiligadda** [go-mysql-org/go-mysql#909]
I am currently utilising go-msql toolset  as proxy to provide SQL interface for my datastores like (ES, CH...). 
My Goal is to ensure this proxy to behave like standard SQL server so that any MySQL client can connect.

To validate this setup, could you please let me know if there is a test suite available that can be used to verify that the proxy  is behaving like standard SQL server.

**Comment by dveeden** [comment]
I'm not aware of any test suite that does this. There is the [MySQL Test](https://dev.mysql.com/doc/dev/mysql-server/latest/PAGE_MYSQL_TEST_RUN.html), but that is testing the syntax rather than the protocol.

The [Client/Server Protocol docs](https://dev.mysql.com/doc/dev/mysql-server/latest/PAGE_PROTOCOL.html) might be useful together with [Wireshark](https://www.wireshark.org/), but that mostly useful if you already have identified a possible issue.

**Comment by kinnera-kokkiligadda** [comment]
Thank you for the info
